"""Tests for the vision-capability probe (vision_probe.py).

Pure unit tests: no network, no Ollama, no committed images. The probe images
are generated by the module's own stdlib PNG encoder, and the transport is a
stub client injected through ``probe_client`` (mirrors test_verify.py's
``_StubClient`` seam). The CLI is driven in-process with ``probe_ollama_model``
monkeypatched.
"""

from __future__ import annotations

import json
import struct
import sys
import zlib
from pathlib import Path

import pytest

# Make src/ importable without installing the package.
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from white_mushroom_test import cli  # noqa: E402
from white_mushroom_test import vision_probe as vp  # noqa: E402
from white_mushroom_test.llm import LLMError  # noqa: E402


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------


def _decode_png_rgb(data: bytes) -> tuple[int, int, tuple[int, int, int]]:
    """Minimal RGB-PNG decoder: return (width, height, first_pixel)."""
    assert data[:8] == b"\x89PNG\r\n\x1a\n", "bad PNG signature"
    offset = 8
    width = height = 0
    idat = b""
    while offset < len(data):
        (length,) = struct.unpack(">I", data[offset : offset + 4])
        tag = data[offset + 4 : offset + 8]
        chunk = data[offset + 8 : offset + 8 + length]
        if tag == b"IHDR":
            width, height, bitdepth, colortype = struct.unpack(">IIBB", chunk[:10])
            assert bitdepth == 8 and colortype == 2, "expected 8-bit truecolor RGB"
        elif tag == b"IDAT":
            idat += chunk
        offset += 12 + length
    raw = zlib.decompress(idat)
    first = raw[1:4]  # skip the filter byte of the first scanline
    return width, height, (first[0], first[1], first[2])


class _MapStub:
    """A client whose answer is keyed by probe image bytes.

    Matches the ``generate_text(prompt, image_b64) -> str`` seam. Missing images
    fall back to the blind answer, so an empty map == a model that cannot see.
    """

    def __init__(self, answers_by_image: dict[str, str], *, raise_exc: BaseException | None = None) -> None:
        self.answers = answers_by_image
        self.raise_exc = raise_exc
        self.calls: list[tuple[str, str]] = []

    def generate_text(self, prompt: str, image_b64: str) -> str:
        self.calls.append((prompt, image_b64))
        if self.raise_exc is not None:
            raise self.raise_exc
        return self.answers.get(image_b64, "I cannot see the image")


def _map(answers_by_name: dict[str, str]) -> dict[str, str]:
    """Translate {probe_name: answer} -> {image_b64: answer} via the spec set."""
    return {spec.image_b64: answers_by_name[spec.name] for spec in vp._SPECS}


def _capable_report(verdict: str = vp.CAPABLE) -> vp.ProbeReport:
    return vp.ProbeReport(provider="ollama", model="stub:model", verdict=verdict, probes=[])


# ---------------------------------------------------------------------------
# PNG encoder round-trip
# ---------------------------------------------------------------------------


def test_solid_png_round_trip() -> None:
    w, h, px = _decode_png_rgb(vp._solid_png(64, 64, (220, 50, 50)))
    assert (w, h) == (64, 64)
    assert px == (220, 50, 50)


def test_count_png_dimensions_and_first_region() -> None:
    w, h, px = _decode_png_rgb(vp._count_png(3, 96, 32))
    assert (w, h) == (96, 32)
    assert px == (220, 50, 50)  # first region is red


# ---------------------------------------------------------------------------
# matchers
# ---------------------------------------------------------------------------


def test_color_match_accepts_synonyms() -> None:
    assert vp._color_match("The dominant color is crimson.", "red") is True
    assert vp._color_match("navy blue", "blue") is True
    assert vp._color_match("green", "red") is False
    assert vp._color_match("a green leaf", "blue") is False


def test_count_match_accepts_digit_or_word() -> None:
    assert vp._count_match("I see 3 regions.", 3) is True
    assert vp._count_match("there are three", 3) is True
    assert vp._count_match("two", 3) is False
    assert vp._count_match("I cannot tell.", 3) is False


def test_answer_invents_object_distinguishes_assertion_from_negation() -> None:
    assert vp._answer_invents_object("a small white mushroom") is True
    assert vp._answer_invents_object("I see no mushroom here.") is False
    assert vp._answer_invents_object("a uniform gray image, nothing visible") is False
    assert vp._answer_invents_object("there is no visible plant or animal") is False


# ---------------------------------------------------------------------------
# probe_client verdicts
# ---------------------------------------------------------------------------


def test_probe_client_seeing_model_is_capable() -> None:
    stub = _MapStub(_map({
        "color_red": "red",
        "color_blue": "blue",
        "count_3": "3",
        "blank": "a uniform gray image",
    }))
    report = vp.probe_client(stub, model="seeing")
    assert report.verdict == vp.CAPABLE
    assert len(report.probes) == 4
    assert all(p.passed for p in report.probes)
    # the model's answers are carried as evidence
    by = {p.name: p.answer for p in report.probes}
    assert by["color_red"] == "red" and by["blank"] == "a uniform gray image"
    assert len(stub.calls) == 4  # every probe fired


def test_probe_client_blind_model_is_text_only() -> None:
    stub = _MapStub({})  # every probe -> blind fallback answer
    report = vp.probe_client(stub, model="blind")
    assert report.verdict == vp.TEXT_ONLY
    # real-content probes failed (no error), blank was honest
    by = {p.name: p for p in report.probes}
    assert by["color_red"].passed is False and by["color_red"].error is None
    assert by["blank"].passed is True


def test_probe_client_hallucinating_model() -> None:
    stub = _MapStub(_map({
        "color_red": "red",
        "color_blue": "blue",
        "count_3": "3",
        "blank": "a small white mushroom",
    }))
    report = vp.probe_client(stub, model="halluc")
    assert report.verdict == vp.HALLUCINATING
    by = {p.name: p for p in report.probes}
    assert by["color_red"].passed is True
    assert by["blank"].passed is False  # invented an object


def test_probe_client_inconsistent_model() -> None:
    stub = _MapStub(_map({
        "color_red": "red",
        "color_blue": "green",   # wrong color
        "count_3": "two",        # wrong count
        "blank": "a blank gray image",
    }))
    report = vp.probe_client(stub, model="mixed")
    assert report.verdict == vp.INCONSISTENT


def test_probe_client_unreachable_model_is_error() -> None:
    stub = _MapStub({}, raise_exc=LLMError("connection refused"))
    report = vp.probe_client(stub, model="down")
    assert report.verdict == vp.ERROR
    # all real-content probes errored, none passed, evidence recorded
    by = {p.name: p for p in report.probes}
    assert by["color_red"].error is not None
    assert by["color_red"].passed is False
    assert by["color_red"].answer == ""


# ---------------------------------------------------------------------------
# CLI main()
# ---------------------------------------------------------------------------


def test_probe_main_json_single_model_capable(monkeypatch, capsys) -> None:
    monkeypatch.setattr(vp, "probe_ollama_model", lambda *a, **k: _capable_report())
    rc = vp.main(["--model", "stub:model", "--json"])
    out = capsys.readouterr().out
    assert rc == 0
    data = json.loads(out)
    assert isinstance(data, list) and data[0]["verdict"] == vp.CAPABLE


def test_probe_main_no_capable_returns_one(monkeypatch, capsys) -> None:
    monkeypatch.setattr(
        vp, "probe_ollama_model", lambda *a, **k: _capable_report(vp.TEXT_ONLY)
    )
    rc = vp.main(["--model", "blind:model"])
    assert rc == 1


def test_probe_main_all_models_rc0_if_any_capable(monkeypatch) -> None:
    monkeypatch.setattr(
        vp,
        "probe_ollama_models",
        lambda *a, **k: [_capable_report(vp.CAPABLE), _capable_report(vp.TEXT_ONLY)],
    )
    rc = vp.main([])
    assert rc == 0


def test_probe_main_list_error_returns_one(monkeypatch, capsys) -> None:
    def _boom(*a, **k):
        raise LLMError("could not list Ollama models at 'x': boom")

    monkeypatch.setattr(vp, "probe_ollama_models", _boom)
    rc = vp.main([])
    assert rc == 1
    assert "error:" in capsys.readouterr().err


def test_cli_probe_dispatch_wires_through_to_vision_probe(monkeypatch, capsys) -> None:
    """The cli.py `probe` subcommand rebuilds argv and delegates to vision_probe.main."""
    monkeypatch.setattr(vp, "probe_ollama_model", lambda *a, **k: _capable_report())
    rc = cli.main(["probe", "--model", "stub:model", "--json"])
    assert rc == 0
    data = json.loads(capsys.readouterr().out)
    assert data[0]["verdict"] == vp.CAPABLE